### ISSUE TITLE
BatchLoaderDelegate HowTo

### ISSUE THREAD

**Issue by mheidt** [graphql-java-generator/GraphQL-Forum-Maven-Tutorial-server#1]
Hello,

What do I need to do, so that BatchLoaderDelegates will be created?

I have some DataFetchers which work with ComputerFuture/BatchLoader.
But those generated dataFetcher functions which are calling the interface funtions in the dataFetcherDelegates are not "future-aware" and expect "real" data types.

I would like to have something like 
BatchLoaderDelegateNodeImpl
but for my own types.

How do I convince graphql-java-generator to create those?

**Comment by etienne-sf** [comment]
Hello, please see my response here: https://github.com/graphql-java-generator/graphql-maven-plugin-project/issues/58
